name: Create pull request templates

on:
  workflow_dispatch:
  schedule:
    - cron: 0 21 * * 0

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request-templates:
    if: ${{ github.repository == 'alextheman231/utility' }}
    uses: alextheman231/github-actions/.github/workflows/create-pull-request-templates.yml@bc9ba5ec23e1006779c9d2971718a32a58fc0b85 # v8.1.0
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
