name: Publish the package

on:
  push:
    branches:
      - main

jobs:
  npm-registry-publish:
    permissions:
      id-token: write
    if: ${{ github.repository == 'alextheman231/utility' }}
    uses: alextheman231/github-actions/.github/workflows/npm-registry-publish.yml@7f9a4bb0d8c993b31a20379938e6591a6f9fa585 # v7.0.0

  create-github-release:
    needs: npm-registry-publish
    permissions:
      contents: write
    if: needs.npm-registry-publish.outputs.did_publish == 'true'
    uses: alextheman231/github-actions/.github/workflows/create-github-release.yml@7f9a4bb0d8c993b31a20379938e6591a6f9fa585 # v7.0.0
    secrets:
      GITHUB_ACTIONS_TOKEN: ${{ secrets.ALEX_UP_BOT_GITHUB_TOKEN }}
